// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: unfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE FROM feed_follows ff
WHERE ff.user_id = $1
AND ff.feed_id IN (SELECT id FROM feeds WHERE url = $2)
`

type UnfollowFeedParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.UserID, arg.Url)
	return err
}
